package slackagent

import (
	"strings"
	"testing"
)

func TestBuildMeetingCanvasMarkdownUsesCueboardSectionsWithoutArtifactLinks(t *testing.T) {
	markdown := buildMeetingCanvasMarkdown(NormalizedMeetingWebhookPayload{
		Title:     "Android Debrief",
		TimeFrom:  "2026-05-14T01:53:16Z",
		TimeTo:    "2026-05-14T01:54:56Z",
		Artifacts: MeetingWebhookArtifacts{TranscriptPath: "https://files.slack.com/transcript.txt", AudioPath: "https://files.slack.com/audio.mp3"},
		Summary: &MeetingSummaryData{
			Attendees:     []string{"Peng Xiao"},
			KeyPoints:     []string{"Android updates are incremental."},
			Decisions:     []string{"Record a short demo."},
			OpenQuestions: []string{"Is Gemini overhyped?"},
			Blockers:      []string{"No blocker."},
			ActionItems: []MeetingActionItem{{
				Description: "Share recap",
				Owner:       "Peng",
				Deadline:    "today",
			}},
		},
	})

	for _, want := range []string{
		"**Duration:** 2 minutes",
		"**Participants:** Peng Xiao",
		"## Key Points",
		"- Android updates are incremental.",
		"## Action Items",
		"- Share recap — **Owner:** Peng — **Deadline:** today",
		"## Decisions",
		"## Open Questions",
		"## Blockers",
		"_Generated by Onee Sama Meeting Bot_",
	} {
		if !strings.Contains(markdown, want) {
			t.Fatalf("markdown missing %q:\n%s", want, markdown)
		}
	}
	if strings.Contains(markdown, "```") ||
		strings.Contains(markdown, "## Transcript") ||
		strings.Contains(markdown, "## Attachments") ||
		strings.Contains(markdown, "transcript.txt") ||
		strings.Contains(markdown, "audio.mp3") ||
		strings.Contains(markdown, "files.slack.com") {
		t.Fatalf("markdown should not expose raw transcript/audio artifact links:\n%s", markdown)
	}
}

func TestBuildMeetingCanvasMarkdownOmitsArtifactSection(t *testing.T) {
	markdown := buildMeetingCanvasMarkdown(NormalizedMeetingWebhookPayload{
		Title:     "Review",
		TimeFrom:  "2026-05-14T04:27:29Z",
		TimeTo:    "2026-05-14T04:29:49Z",
		Artifacts: MeetingWebhookArtifacts{TranscriptPath: "https://files.slack.com/transcript.txt", AudioPath: "https://files.slack.com/audio.mp3"},
		Summary: &MeetingSummaryData{
			Attendees: []string{"Peng Xiao"},
			KeyPoints: []string{"Captured captions."},
		},
	})
	want := strings.Join([]string{
		"**Duration:** 3 minutes",
		"",
		"**Participants:** Peng Xiao",
		"",
		"## Key Points",
		"",
		"- Captured captions.",
		"",
		"---",
		"_Generated by Onee Sama Meeting Bot_",
		"",
	}, "\n")
	if markdown != want {
		t.Fatalf("markdown mismatch\nwant:\n%s\ngot:\n%s", want, markdown)
	}
}

func TestCueboardParityMeetingCanvasMarkdownDoesNotDrift(t *testing.T) {
	markdown := buildMeetingCanvasMarkdown(NormalizedMeetingWebhookPayload{
		Title:     "Triage parity review",
		TimeFrom:  "2026-05-14T10:00:00Z",
		TimeTo:    "2026-05-14T10:05:00Z",
		Artifacts: MeetingWebhookArtifacts{TranscriptPath: "https://files.slack.com/transcript.txt"},
		Summary: &MeetingSummaryData{
			Attendees: []string{"Peng Xiao", "Onee Sama"},
			KeyPoints: []string{"Cueboard sections stay stable."},
		},
	})
	want := strings.Join([]string{
		"**Duration:** 5 minutes",
		"",
		"**Participants:** Peng Xiao, Onee Sama",
		"",
		"## Key Points",
		"",
		"- Cueboard sections stay stable.",
		"",
		"---",
		"_Generated by Onee Sama Meeting Bot_",
		"",
	}, "\n")
	if markdown != want {
		t.Fatalf("meeting Canvas markdown drifted from cueboard shape\nwant:\n%s\ngot:\n%s", want, markdown)
	}
}

func TestBuildMeetingResultPostDoesNotExposeArtifactPaths(t *testing.T) {
	text := buildMeetingResultPost(NormalizedMeetingWebhookPayload{
		Title: "Review",
		Artifacts: MeetingWebhookArtifacts{
			TranscriptPath: "https://files.slack.com/transcript.txt",
			AudioPath:      "/tmp/private/audio.wav",
		},
		Summary: &MeetingSummaryData{KeyPoints: []string{"Captured captions."}},
	})
	for _, leaked := range []string{"Artifacts", "Transcript:", "Audio:", "transcript.txt", "audio.wav", "files.slack.com", "/tmp/private"} {
		if strings.Contains(text, leaked) {
			t.Fatalf("meeting result post leaked artifact %q:\n%s", leaked, text)
		}
	}
}
