export interface MeetingAgentInput {
  url?: string;
  useJina?: boolean;
  use_jina?: boolean;
  maxChars?: number | string;
  max_chars?: number | string;
  maxAttempts?: number | string;
  max_attempts?: number | string;
  maxResults?: number | string;
  max_results?: number | string;
  query?: string;
  limit?: number | string;
  count?: number | string;
  user?: string;
  data?: unknown;
  channel?: string;
  message?: string;
  meet_url?: string;
  meetUrl?: string;
  meetingId?: string;
  meeting_id?: string;
  jobId?: string;
  job_id?: string;
  id?: string;
  key?: string;
  kind?: string;
  mode?: string;
  model?: string;
  event?: unknown;
  format?: string;
  reasoning?: unknown;
  reasoningEffort?: string;
  reasoning_effort?: string;
  output_modalities?: string[];
  outputModalities?: string[];
  voice?: string;
  audio?: unknown;
  avatar?: unknown;
  context?: unknown;
  task?: string;
  text?: string;
  utterance?: string;
  reason?: string;
  preview?: boolean;
  dryRun?: boolean;
  dry_run_joiner?: boolean;
  dryRunJoiner?: boolean;
  recordMeeting?: boolean;
  installLocalDialogBridge?: boolean;
  installRealtimeBridge?: boolean;
  installScreenShareBridge?: boolean;
  installWorkerResultBridge?: boolean;
  realtimeBridgeMode?: string;
  realtimeAgentRuntime?: string;
  realtimeRuntimePlacement?: string;
  realtimeInstructions?: string;
  realtimeSdpUrl?: string;
  realtimeTokenUrl?: string;
  meetAudioBackend?: string;
  forwardMeetAudioToRealtime?: boolean;
  includeParticipantAudio?: boolean;
  autoConnectRealtime?: boolean;
  autoStartScreenShare?: boolean;
  botName?: string;
  captureCaptions?: boolean;
  captionLanguage?: string;
  disableLive2D?: boolean;
  collectFixtureState?: boolean;
  allowNonGoogleMeet?: boolean;
  artifactsDir?: string;
  localDialogTurnUrl?: string;
  localDialogSttProvider?: string;
  localDialogTtsProvider?: string;
  localDialogTtsMode?: string;
  localDialogTtsUrl?: string;
  localDialogTtsGain?: number;
  localDialogAcceptanceUtterance?: string;
  dedupKey?: string;
  markDelivered?: boolean;
  minCreatedAt?: string;
  mock?: boolean;
  muted?: boolean;
  now?: string;
  onlyLinks?: boolean;
  only_links?: boolean;
  path?: string;
  durationMs?: number;
  frequency?: number;
  gain?: number;
  height?: number;
  instructions?: string;
  at?: string;
  allowCodeChanges?: boolean;
  chat_transcript?: string;
  chatTranscript?: string;
  result?: string | Record<string, unknown>;
  error?: string;
  status?: string;
  wait?: boolean;
  [key: string]: unknown;
}
